import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { kitCategoryLabel } from './crewKit';
import { loadLogoForPdf } from '../../crew-management/utils/guestBookExport';

const CARGO_LOGO = '/assets/images/cargo_merged_originalmark_syne800_true.png';

const NAVY = [28, 27, 58];
const TERRA = [198, 90, 26];
const MUTED = [139, 132, 120];
const HAIR = [236, 234, 227];

const dd = (d) => {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(d || ''));
  return m ? `${m[3]}/${m[2]}/${m[1]}` : '';
};
const statusText = (it) => {
  if (it.status === 'returned') return `Returned ${dd(it.returned_date)}`.trim();
  if (it.status === 'lost') return 'Lost / damaged';
  if (it.swap_requested_size) return `Swap requested (${it.swap_requested_size})`;
  return it.acknowledged_at ? 'In service' : 'Awaiting acknowledgement';
};
const STATUS_RANK = { in_service: 0, returned: 1, lost: 2 };

// Condense identical lines into one — same item / size / category / serial /
// status collapse to a single row with the quantities summed (so three "Crew
// polo · M · in service" rows read as one "×3"). Differing issue / ack dates
// within a merged line show as "various".
const oneOrVarious = (set) => (set.size === 0 ? '' : set.size === 1 ? [...set][0] : 'various');
const condense = (list) => {
  const m = new Map();
  list.forEach((it) => {
    const label = statusText(it);
    const key = [it.item || '', it.size || '', it.category || '', it.serial || '', label].join('|');
    if (!m.has(key)) m.set(key, { item: it.item, size: it.size, category: it.category, serial: it.serial, status: it.status, label, qty: 0, issued: new Set(), ack: new Set() });
    const g = m.get(key);
    g.qty += Number(it.quantity) || 1;
    if (it.issued_date) g.issued.add(dd(it.issued_date));
    g.ack.add(it.acknowledged_at ? dd(it.acknowledged_at) : '—');
  });
  return [...m.values()].sort((a, b) =>
    ((STATUS_RANK[a.status] ?? 3) - (STATUS_RANK[b.status] ?? 3))
    || a.label.localeCompare(b.label)
    || (a.item || '').localeCompare(b.item || '')
    || (a.size || '').localeCompare(b.size || ''));
};

/**
 * A4 kit issue/return receipt — the digital version of the paper hand-out
 * sheet. `ackSig` / `returnSig` are PNG data URLs (or null). Items in service
 * are listed first, then returned / lost (greyed). A footer (Cargo mark +
 * generated date + page number) is stamped on every page, and the declaration
 * and signature blocks are kept whole — pushed to a fresh page rather than
 * colliding with the footer.
 */
export const exportKitReceipt = async ({ crewName, vesselName, vessel, generatedAt, items, ackSig, returnSig, scopeLabel }) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M = 16;
  const FOOTER_RESERVE = 24; // band kept clear at the bottom of every page

  // Load the Cargo mark up-front so the footer can be stamped on every page.
  const logo = await loadLogoForPdf(CARGO_LOGO);
  const drawFooter = (page, total) => {
    if (logo?.dataUrl) {
      const logoH = 4.4;
      const logoW = logoH * (logo.aspect || 6.7);
      try { doc.addImage(logo.dataUrl, 'PNG', M, pageH - 12, logoW, logoH); } catch { /* skip */ }
    } else {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
      doc.text('Generated by Cargo — yacht crew management', M, pageH - 10);
    }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
    const right = [generatedAt ? `Generated ${generatedAt}` : null, total > 1 ? `Page ${page} / ${total}` : null].filter(Boolean).join('    ·    ');
    if (right) doc.text(right, pageW - M, pageH - 9, { align: 'right' });
  };

  // Header
  doc.setTextColor(...TERRA);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9);
  doc.text('ISSUED KIT — RECEIPT & RESPONSIBILITY RECORD', M, 20);
  doc.setTextColor(...NAVY);
  doc.setFont('times', 'normal'); doc.setFontSize(22);
  doc.text(crewName || 'Crew member', M, 30);

  // Vessel identity anchors this to a specific ship — it's a responsibility record.
  const vName = vessel?.name || vesselName;
  const idLine = [vName, vessel?.flag, vessel?.port_of_registry, vessel?.imo_number && `IMO ${vessel.imo_number}`]
    .filter(Boolean).join('   ·   ');
  let hy = 37;
  if (idLine) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...NAVY);
    doc.text(idLine, M, hy);
    hy += 5;
  }
  doc.setDrawColor(...HAIR); doc.line(M, hy, pageW - M, hy);

  // Condense duplicates, then summarise the register at a glance.
  const rows = condense(items);
  const unitsOf = (st) => rows.filter((r) => r.status === st).reduce((a, r) => a + r.qty, 0);
  const inServUnits = unitsOf('in_service');
  const returnedUnits = unitsOf('returned');
  const lostUnits = unitsOf('lost');
  const awaiting = rows.filter((r) => r.status === 'in_service' && r.label === 'Awaiting acknowledgement').reduce((a, r) => a + r.qty, 0);
  const totalUnits = rows.reduce((a, r) => a + r.qty, 0);
  const summary = [
    scopeLabel ? scopeLabel.toUpperCase() : null,
    `${totalUnits} item${totalUnits === 1 ? '' : 's'}`,
    `${inServUnits} in service`,
    returnedUnits ? `${returnedUnits} returned` : null,
    lostUnits ? `${lostUnits} lost / damaged` : null,
    awaiting ? `${awaiting} awaiting sign-off` : null,
  ].filter(Boolean).join('     ·     ');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
  doc.text(summary, M, hy + 6);
  const tableStart = hy + 12;

  // Items — condensed, in service first, then returned / lost (retired greyed).
  autoTable(doc, {
    startY: tableStart,
    margin: { left: M, right: M, bottom: FOOTER_RESERVE },
    head: [['Item', 'Category', 'Size', 'Qty', 'Serial', 'Issued', 'Acknowledged', 'Status']],
    body: rows.map((r) => [
      r.item || '',
      kitCategoryLabel(r.category),
      r.size || '',
      String(r.qty),
      r.serial || '',
      oneOrVarious(r.issued),
      oneOrVarious(r.ack),
      r.label,
    ]),
    styles: { font: 'helvetica', fontSize: 8.5, cellPadding: 2.4, textColor: NAVY, lineColor: HAIR, lineWidth: 0.1 },
    headStyles: { fillColor: [250, 250, 248], textColor: MUTED, fontStyle: 'bold', fontSize: 7.5, lineColor: HAIR, lineWidth: 0.1 },
    alternateRowStyles: { fillColor: [252, 251, 248] },
    columnStyles: { 3: { halign: 'center' } },
    // Grey the retired rows so in-service kit reads as the live record.
    didParseCell: (data) => {
      if (data.section !== 'body') return;
      const r = rows[data.row.index];
      if (r && r.status !== 'in_service') data.cell.styles.textColor = MUTED;
    },
  });

  let y = (doc.lastAutoTable?.finalY || 60) + 14;

  // Declaration + signatures — keep them whole. If they won't clear the footer,
  // start them on a fresh page rather than letting them run under the Cargo mark.
  doc.setFont('helvetica', 'italic'); doc.setFontSize(9.5);
  const decl = 'I confirm I have received the items listed above and accept responsibility for their care and safe return.';
  const declLines = doc.splitTextToSize(decl, pageW - 2 * M);
  const blockNeed = declLines.length * 5 + 9 + 32; // declaration + gap + signature block
  if (y + blockNeed > pageH - FOOTER_RESERVE) { doc.addPage(); y = 24; }

  doc.setTextColor(...NAVY); doc.setFont('helvetica', 'italic'); doc.setFontSize(9.5);
  doc.text(declLines, M, y);
  y += declLines.length * 5 + 9;

  // Signature blocks — crew acknowledgement (left) + return sign-off (right).
  const colW = (pageW - 2 * M - 12) / 2;
  const ackItem = items.find((i) => i.ack_signed_name) || items.find((i) => i.acknowledged_at);
  const retItem = items.find((i) => i.return_signed_name) || items.find((i) => i.status === 'returned');
  const sigBlock = (x, title, img, name, when) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
    doc.text(title.toUpperCase(), x, y);
    if (img) { try { doc.addImage(img, 'PNG', x, y + 3, 48, 15); } catch { /* bad image */ } }
    doc.setDrawColor(...HAIR); doc.line(x, y + 21, x + colW, y + 21);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...NAVY);
    if (name) doc.text(name, x, y + 26);
    if (when) { doc.setFontSize(7.5); doc.setTextColor(...MUTED); doc.text(when, x, y + 30.5); }
  };
  sigBlock(M, 'Crew — acknowledged receipt', ackSig, ackItem?.ack_signed_name, ackItem?.acknowledged_at ? dd(ackItem.acknowledged_at) : '');
  sigBlock(M + colW + 12, 'Returned to (signature)', returnSig, retItem?.return_signed_name, retItem?.returned_date ? dd(retItem.returned_date) : '');

  // Stamp the footer on every page (drawn last so page count is final).
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p += 1) { doc.setPage(p); drawFooter(p, total); }

  const safe = (crewName || 'crew').replace(/[^\w]+/g, '-');
  doc.save(`Kit-receipt-${safe}.pdf`);
};
