import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { kitCategoryLabel } from './crewKit';
import { loadLogoForPdf } from '../../crew-management/utils/guestBookExport';

const CARGO_LOGO = '/assets/images/cargo_merged_originalmark_syne800_true.png';

const NAVY = [28, 27, 58];
const TERRA = [198, 90, 26];
const MUTED = [139, 132, 120];
const HAIR = [236, 234, 227];

const dd = (d) => {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(d || ''));
  return m ? `${m[3]}/${m[2]}/${m[1]}` : '';
};
const statusText = (it) => {
  if (it.status === 'returned') return `Returned ${dd(it.returned_date)}`.trim();
  if (it.status === 'lost') return 'Lost / damaged';
  if (it.swap_requested_size) return `Swap requested (${it.swap_requested_size})`;
  return it.acknowledged_at ? 'In service' : 'Awaiting acknowledgement';
};
const STATUS_RANK = { in_service: 0, returned: 1, lost: 2 };

const oneOrVarious = (set) => (set.size === 0 ? '' : set.size === 1 ? [...set][0] : 'various');

// Sort sizes into wearing order (XS→XXL, then numeric; "one size" last).
const SIZE_RANK = { XXS: 0, XS: 1, S: 2, M: 3, L: 4, XL: 5, '2XL': 6, XXL: 6, '3XL': 7, XXXL: 7 };
const sizeSort = (a, b) => {
  const A = String(a || '').toUpperCase().trim(); const B = String(b || '').toUpperCase().trim();
  if (A === B) return 0; if (!A) return 1; if (!B) return -1;
  const ra = SIZE_RANK[A]; const rb = SIZE_RANK[B];
  if (ra != null && rb != null) return ra - rb;
  if (ra != null) return -1; if (rb != null) return 1;
  const na = parseFloat(A); const nb = parseFloat(B);
  if (!Number.isNaN(na) && !Number.isNaN(nb)) return na - nb;
  return A.localeCompare(B);
};

// Group by item + category + status, nesting each size beneath the item (mirrors
// the fleet register). Serial / issued date collapse to one value or "various"
// across the item's sizes. In-service first, then returned / lost.
const buildGroups = (list) => {
  const m = new Map();
  list.forEach((it) => {
    const label = statusText(it);
    const key = [(it.item || '').toLowerCase(), it.category || '', label].join('|');
    if (!m.has(key)) m.set(key, { item: it.item, category: it.category, status: it.status, label, sizes: new Map(), serials: new Set(), issued: new Set() });
    const g = m.get(key);
    const sz = (it.size || '').trim();
    g.sizes.set(sz, (g.sizes.get(sz) || 0) + (Number(it.quantity) || 1));
    if (it.serial) g.serials.add(it.serial);
    if (it.issued_date) g.issued.add(dd(it.issued_date));
  });
  return [...m.values()].map((g) => {
    const sizes = [...g.sizes.entries()].map(([size, qty]) => ({ size, qty })).sort((a, b) => sizeSort(a.size, b.size));
    return { ...g, sizes, total: sizes.reduce((a, s) => a + s.qty, 0) };
  }).sort((a, b) =>
    ((STATUS_RANK[a.status] ?? 3) - (STATUS_RANK[b.status] ?? 3))
    || a.label.localeCompare(b.label)
    || (a.item || '').localeCompare(b.item || ''));
};

/**
 * A4 kit issue/return receipt — the digital version of the paper hand-out
 * sheet. `ackSig` / `returnSig` are PNG data URLs (or null). Items in service
 * are listed first, then returned / lost (greyed). A footer (Cargo mark +
 * generated date + page number) is stamped on every page, and the declaration
 * and signature blocks are kept whole — pushed to a fresh page rather than
 * colliding with the footer.
 */
export const exportKitReceipt = async ({ crewName, vesselName, vessel, generatedAt, items, ackSig, returnSig, scopeLabel }) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M = 16;
  const FOOTER_RESERVE = 24; // band kept clear at the bottom of every page

  // Load the Cargo mark up-front so the footer can be stamped on every page.
  const logo = await loadLogoForPdf(CARGO_LOGO);
  const drawFooter = (page, total) => {
    if (logo?.dataUrl) {
      const logoH = 4.4;
      const logoW = logoH * (logo.aspect || 6.7);
      try { doc.addImage(logo.dataUrl, 'PNG', M, pageH - 12, logoW, logoH); } catch { /* skip */ }
    } else {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
      doc.text('Generated by Cargo — yacht crew management', M, pageH - 10);
    }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
    const right = [generatedAt ? `Generated ${generatedAt}` : null, total > 1 ? `Page ${page} / ${total}` : null].filter(Boolean).join('    ·    ');
    if (right) doc.text(right, pageW - M, pageH - 9, { align: 'right' });
  };

  // Header
  doc.setTextColor(...TERRA);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9);
  doc.text('ISSUED KIT — RECORD & RESPONSIBILITY', M, 20);
  doc.setTextColor(...NAVY);
  doc.setFont('times', 'normal'); doc.setFontSize(22);
  doc.text(crewName || 'Crew member', M, 30);

  // Vessel identity anchors this to a specific ship — it's a responsibility record.
  const vName = vessel?.name || vesselName;
  const idLine = [vName, vessel?.flag, vessel?.port_of_registry, vessel?.imo_number && `IMO ${vessel.imo_number}`]
    .filter(Boolean).join('   ·   ');
  let hy = 37;
  if (idLine) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...NAVY);
    doc.text(idLine, M, hy);
    hy += 5;
  }
  doc.setDrawColor(...HAIR); doc.line(M, hy, pageW - M, hy);

  // Group by item (sizes nested), then summarise at a glance.
  const groups = buildGroups(items);
  const unitsOf = (st) => groups.filter((g) => g.status === st).reduce((a, g) => a + g.total, 0);
  const inServUnits = unitsOf('in_service');
  const returnedUnits = unitsOf('returned');
  const lostUnits = unitsOf('lost');
  const awaiting = groups.filter((g) => g.status === 'in_service' && g.label === 'Awaiting acknowledgement').reduce((a, g) => a + g.total, 0);
  const totalUnits = groups.reduce((a, g) => a + g.total, 0);
  const summary = [
    scopeLabel ? scopeLabel.toUpperCase() : null,
    `${totalUnits} item${totalUnits === 1 ? '' : 's'}`,
    `${inServUnits} in service`,
    returnedUnits ? `${returnedUnits} returned` : null,
    lostUnits ? `${lostUnits} lost / damaged` : null,
    awaiting ? `${awaiting} awaiting sign-off` : null,
  ].filter(Boolean).join('     ·     ');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
  doc.text(summary, M, hy + 6);
  const tableStart = hy + 12;

  // One merged Item row per item, each size on its own line beneath — matching
  // the fleet register. Category / Serial / Issued / Status span via rowSpan;
  // shading is per item (theme 'grid' so autoTable adds no zebra of its own).
  const head = [['Category', 'Item', 'Size', 'Qty', 'Serial', 'Issued', 'Status']];
  const body = [];
  const stripeByRow = [];
  const retiredByRow = [];
  let gi = 0;
  groups.forEach((g) => {
    const sizes = g.sizes.length ? g.sizes : [{ size: '', qty: g.total }];
    const n = sizes.length;
    const stripe = gi % 2 === 1;
    const retired = g.status !== 'in_service';
    const itemText = n > 1 ? `${g.item || ''}\n${g.total} total` : (g.item || '');
    sizes.forEach((s, idx) => {
      if (idx === 0) {
        body.push([
          { content: kitCategoryLabel(g.category), rowSpan: n, styles: { textColor: MUTED, fontStyle: 'bold', valign: 'middle' } },
          { content: itemText, rowSpan: n, styles: { valign: 'middle' } },
          s.size || 'One size',
          String(s.qty),
          { content: oneOrVarious(g.serials), rowSpan: n, styles: { valign: 'middle' } },
          { content: oneOrVarious(g.issued), rowSpan: n, styles: { valign: 'middle' } },
          { content: g.label, rowSpan: n, styles: { valign: 'middle' } },
        ]);
      } else {
        body.push([s.size || 'One size', String(s.qty)]);
      }
      stripeByRow.push(stripe); retiredByRow.push(retired);
    });
    gi += 1;
  });

  autoTable(doc, {
    startY: tableStart,
    margin: { left: M, right: M, bottom: FOOTER_RESERVE },
    head, body,
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 2.6, textColor: NAVY, fillColor: [255, 255, 255], lineColor: HAIR, lineWidth: 0.1 },
    headStyles: { fillColor: [250, 250, 248], textColor: MUTED, fontStyle: 'bold', fontSize: 7.5, lineColor: HAIR, lineWidth: 0.1 },
    columnStyles: {
      0: { cellWidth: 34 }, 1: { cellWidth: 84 }, 2: { cellWidth: 30 },
      3: { halign: 'center', cellWidth: 16 }, 4: { cellWidth: 36 }, 5: { cellWidth: 28 }, 6: { cellWidth: 38 },
    },
    didParseCell: (data) => {
      if (data.section !== 'body') return;
      if (stripeByRow[data.row.index]) data.cell.styles.fillColor = [252, 251, 248];
      if (retiredByRow[data.row.index]) data.cell.styles.textColor = MUTED;
    },
  });

  let y = (doc.lastAutoTable?.finalY || 60) + 14;

  // Declaration + signatures — keep them whole. If they won't clear the footer,
  // start them on a fresh page rather than letting them run under the Cargo mark.
  doc.setFont('helvetica', 'italic'); doc.setFontSize(9.5);
  const decl = 'I confirm I have received the items listed above and accept responsibility for their care and safe return.';
  const declLines = doc.splitTextToSize(decl, pageW - 2 * M);
  const blockNeed = declLines.length * 5 + 9 + 32; // declaration + gap + signature block
  if (y + blockNeed > pageH - FOOTER_RESERVE) { doc.addPage(); y = 24; }

  doc.setTextColor(...NAVY); doc.setFont('helvetica', 'italic'); doc.setFontSize(9.5);
  doc.text(declLines, M, y);
  y += declLines.length * 5 + 9;

  // Signature blocks — crew acknowledgement (left) + return sign-off (right).
  const colW = (pageW - 2 * M - 12) / 2;
  const ackItem = items.find((i) => i.ack_signed_name) || items.find((i) => i.acknowledged_at);
  const retItem = items.find((i) => i.return_signed_name) || items.find((i) => i.status === 'returned');
  const sigBlock = (x, title, img, name, when) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
    doc.text(title.toUpperCase(), x, y);
    if (img) { try { doc.addImage(img, 'PNG', x, y + 3, 48, 15); } catch { /* bad image */ } }
    doc.setDrawColor(...HAIR); doc.line(x, y + 21, x + colW, y + 21);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...NAVY);
    if (name) doc.text(name, x, y + 26);
    if (when) { doc.setFontSize(7.5); doc.setTextColor(...MUTED); doc.text(when, x, y + 30.5); }
  };
  sigBlock(M, 'Crew — acknowledged', ackSig, ackItem?.ack_signed_name, ackItem?.acknowledged_at ? dd(ackItem.acknowledged_at) : '');
  sigBlock(M + colW + 12, 'Returned to (signature)', returnSig, retItem?.return_signed_name, retItem?.returned_date ? dd(retItem.returned_date) : '');

  // Stamp the footer on every page (drawn last so page count is final).
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p += 1) { doc.setPage(p); drawFooter(p, total); }

  const safe = (crewName || 'crew').replace(/[^\w]+/g, '-');
  doc.save(`Kit-record-${safe}.pdf`);
};
