import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { kitCategoryLabel } from './crewKit';

const NAVY = [28, 27, 58];
const TERRA = [198, 90, 26];
const MUTED = [139, 132, 120];
const HAIR = [236, 234, 227];

const dd = (d) => {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(d || ''));
  return m ? `${m[3]}/${m[2]}/${m[1]}` : '';
};
const statusText = (it) => {
  if (it.status === 'returned') return `Returned ${dd(it.returned_date)}`.trim();
  if (it.status === 'lost') return 'Lost / damaged';
  return it.acknowledged_at ? 'In service' : 'Awaiting acknowledgement';
};

/**
 * A4 kit issue/return receipt — the digital version of the paper hand-out
 * sheet. `ackSig` / `returnSig` are PNG data URLs (or null).
 */
export const exportKitReceipt = ({ crewName, vesselName, generatedAt, items, ackSig, returnSig }) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const M = 16;

  // Header
  doc.setTextColor(...TERRA);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9);
  doc.text('ISSUED KIT — RECEIPT & RESPONSIBILITY RECORD', M, 20);
  doc.setTextColor(...NAVY);
  doc.setFont('times', 'normal'); doc.setFontSize(22);
  doc.text(crewName || 'Crew member', M, 30);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...MUTED);
  const sub = [vesselName, generatedAt && `Generated ${generatedAt}`].filter(Boolean).join('   ·   ');
  if (sub) doc.text(sub, M, 37);
  doc.setDrawColor(...HAIR); doc.line(M, 41, pageW - M, 41);

  // Items table
  autoTable(doc, {
    startY: 47,
    margin: { left: M, right: M },
    head: [['Item', 'Category', 'Size', 'Qty', 'Serial', 'Issued', 'Acknowledged', 'Status']],
    body: items.map((it) => [
      it.item || '',
      kitCategoryLabel(it.category),
      it.size || '',
      String(it.quantity || 1),
      it.serial || '',
      dd(it.issued_date),
      it.acknowledged_at ? dd(it.acknowledged_at) : '—',
      statusText(it),
    ]),
    styles: { font: 'helvetica', fontSize: 8.5, cellPadding: 2.4, textColor: NAVY, lineColor: HAIR, lineWidth: 0.1 },
    headStyles: { fillColor: [250, 250, 248], textColor: MUTED, fontStyle: 'bold', fontSize: 7.5, lineColor: HAIR, lineWidth: 0.1 },
    alternateRowStyles: { fillColor: [252, 251, 248] },
    columnStyles: { 3: { halign: 'center' } },
  });

  let y = (doc.lastAutoTable?.finalY || 60) + 14;

  // Declaration
  doc.setTextColor(...NAVY); doc.setFont('helvetica', 'italic'); doc.setFontSize(9.5);
  const decl = 'I confirm I have received the items listed above and accept responsibility for their care and safe return.';
  doc.text(doc.splitTextToSize(decl, pageW - 2 * M), M, y);
  y += 14;

  // Signature blocks — crew acknowledgement (left) + return sign-off (right)
  const colW = (pageW - 2 * M - 12) / 2;
  const sigBlock = (x, title, img, name) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
    doc.text(title.toUpperCase(), x, y);
    if (img) { try { doc.addImage(img, 'PNG', x, y + 3, 50, 16); } catch { /* bad image */ } }
    doc.setDrawColor(...HAIR); doc.line(x, y + 22, x + colW, y + 22);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...NAVY);
    if (name) doc.text(name, x, y + 27);
  };
  sigBlock(M, 'Crew — acknowledged receipt', ackSig, items.find((i) => i.ack_signed_name)?.ack_signed_name);
  sigBlock(M + colW + 12, 'Returned to (signature)', returnSig, items.find((i) => i.return_signed_name)?.return_signed_name);

  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
  doc.text('Generated by Cargo — yacht crew management', M, doc.internal.pageSize.getHeight() - 10);

  const safe = (crewName || 'crew').replace(/[^\w]+/g, '-');
  doc.save(`Kit-receipt-${safe}.pdf`);
};
