import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { money } from './laundryBilling';
import { loadLogoForPdf } from '../../crew-management/utils/guestBookExport';

const CARGO_LOGO = '/assets/images/cargo_merged_originalmark_syne800_true.png';
const NAVY = [28, 27, 58];
const TERRA = [198, 90, 26];
const MUTED = [139, 132, 120];
const HAIR = [236, 234, 227];

// A4 "crew kit — issued register": every in-service item across the crew, grouped
// into the same sections as the app (uniform by charter → type, then equipment),
// with a Category column, per-line quantity and how many crew hold each.
export const exportCrewKitList = async ({ vesselName, vessel, generatedAt, groups = [], showValue, scopeLabel }) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const M = 16;

  const logo = await loadLogoForPdf(CARGO_LOGO);
  const drawFooter = (page, count) => {
    if (logo?.dataUrl) {
      const h = 4.4; const w = h * (logo.aspect || 6.7);
      try { doc.addImage(logo.dataUrl, 'PNG', M, pageH - 12, w, h); } catch { /* skip */ }
    } else {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
      doc.text('Generated by Cargo — yacht crew management', M, pageH - 10);
    }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
    const right = [generatedAt ? `Generated ${generatedAt}` : null, count > 1 ? `Page ${page} / ${count}` : null].filter(Boolean).join('    ·    ');
    if (right) doc.text(right, pageW - M, pageH - 9, { align: 'right' });
  };

  // Header
  doc.setTextColor(...TERRA); doc.setFont('helvetica', 'bold'); doc.setFontSize(9);
  doc.text('CREW KIT — ISSUED REGISTER', M, 20);
  doc.setTextColor(...NAVY); doc.setFont('times', 'normal'); doc.setFontSize(22);
  doc.text(vessel?.name || vesselName || 'Vessel', M, 30);
  const idLine = [vessel?.flag, vessel?.port_of_registry, vessel?.imo_number && `IMO ${vessel.imo_number}`].filter(Boolean).join('   ·   ');
  let hy = 37;
  if (idLine) { doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.text(idLine, M, hy); hy += 5; }
  doc.setDrawColor(...HAIR); doc.line(M, hy, pageW - M, hy);

  const totalUnits = groups.reduce((a, g) => a + (g.units || g.rows.reduce((x, r) => x + r.qty, 0)), 0);
  const totalLines = groups.reduce((a, g) => a + g.rows.length, 0);
  const summary = [scopeLabel || 'In service', `${totalUnits} item${totalUnits === 1 ? '' : 's'}`, `${totalLines} line${totalLines === 1 ? '' : 's'}`].join('     ·     ');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(...MUTED);
  doc.text(summary.toUpperCase(), M, hy + 6);

  const head = [['Category', 'Item', 'Sizes', 'Qty', 'Crew', ...(showValue ? ['Value'] : [])]];
  const body = [];
  groups.forEach((g) => g.rows.forEach((r) => {
    const total = r.total != null ? r.total : Number(r.qty) || 0;
    const sizeStr = Array.isArray(r.sizes) && r.sizes.length
      ? r.sizes.map((s) => `${s.size || 'One size'} ×${s.qty}`).join('   ')
      : (r.size || '');
    body.push([
      g.title, r.item || '', sizeStr, String(total), String(r.holders),
      ...(showValue ? [r.value != null ? money(r.value * total, 'USD') : ''] : []),
    ]);
  }));

  autoTable(doc, {
    startY: hy + 12,
    margin: { left: M, right: M, bottom: 20 },
    head, body,
    styles: { font: 'helvetica', fontSize: 8.5, cellPadding: 2.4, textColor: NAVY, lineColor: HAIR, lineWidth: 0.1 },
    headStyles: { fillColor: [250, 250, 248], textColor: MUTED, fontStyle: 'bold', fontSize: 7.5, lineColor: HAIR, lineWidth: 0.1 },
    alternateRowStyles: { fillColor: [252, 251, 248] },
    columnStyles: { 0: { textColor: MUTED, fontStyle: 'bold', cellWidth: 30 }, 3: { halign: 'center' }, 4: { halign: 'center' } },
  });

  const count = doc.getNumberOfPages();
  for (let p = 1; p <= count; p += 1) { doc.setPage(p); drawFooter(p, count); }

  const safe = (vessel?.name || vesselName || 'vessel').replace(/[^\w]+/g, '-');
  doc.save(`Crew-kit-register-${safe}.pdf`);
};
