export const ORDERS = [
  {
    id: 'CGO-2026-0418',
    yacht: 'M/Y Solstice',
    yachtShort: 'SOL', yachtColor: 'm3',
    yachtMeta: 'Chief stew Amelia · 72m',
    received: 'Mon 06:42',
    receivedAgo: '4h ago',
    items: 38, flagged: 2,
    deliverBy: 'Thu 23 Apr',
    deliverTime: '06:00 · Antibes',
    status: 'new',
    statusLbl: 'Awaiting confirmation',
    value: '€ 5,127.20',
    rush: true,
    isNew: true,
    notes: 'Charter start',
  },
  {
    id: 'CGO-2026-0417',
    yacht: 'M/Y Aether',
    yachtShort: 'AET', yachtColor: 'm2',
    yachtMeta: 'Purser Elena · 58m',
    received: 'Mon 05:18',
    receivedAgo: '6h ago',
    items: 22, flagged: 0,
    deliverBy: 'Wed 22 Apr',
    deliverTime: '14:00 · Cannes',
    status: 'new',
    statusLbl: 'New',
    value: '€ 2,840.10',
    rush: false, isNew: true,
  },
  {
    id: 'CGO-2026-0416',
    yacht: 'S/Y Corvus',
    yachtShort: 'COR', yachtColor: 'm5',
    yachtMeta: 'Chef Tomás · 44m',
    received: 'Sun 22:04',
    receivedAgo: 'yesterday',
    items: 14, flagged: 1,
    deliverBy: 'Tue 21 Apr',
    deliverTime: '09:00 · Antibes',
    status: 'new',
    statusLbl: 'New · price query',
    value: '€ 1,216.40',
    rush: false, isNew: true,
  },
  {
    id: 'CGO-2026-0415',
    yacht: 'M/Y Lumen',
    yachtShort: 'LUM', yachtColor: 'm4',
    yachtMeta: 'Chief stew Ria · 66m',
    received: 'Sun 18:40',
    receivedAgo: 'yesterday',
    items: 9, flagged: 0,
    deliverBy: 'Tue 21 Apr',
    deliverTime: '10:30 · Monaco',
    status: 'new',
    statusLbl: 'New',
    value: '€ 684.90',
    rush: false, isNew: true,
  },
  {
    id: 'CGO-2026-0412',
    yacht: 'M/Y Aether',
    yachtShort: 'AET', yachtColor: 'm2',
    yachtMeta: 'Purser Elena · 58m',
    received: 'Fri 14:22',
    receivedAgo: '3d',
    items: 31, flagged: 0,
    deliverBy: 'Tue 21 Apr',
    deliverTime: '07:00 · Cannes',
    status: 'confirmed',
    statusLbl: 'Confirmed',
    value: '€ 3,680.00',
  },
  {
    id: 'CGO-2026-0410',
    yacht: 'M/Y Solstice',
    yachtShort: 'SOL', yachtColor: 'm3',
    yachtMeta: 'Chief stew Amelia · 72m',
    received: 'Fri 09:14',
    receivedAgo: '3d',
    items: 18, flagged: 0,
    deliverBy: 'Mon 20 Apr',
    deliverTime: '16:00 · Antibes',
    status: 'dispatched',
    statusLbl: 'Dispatched',
    value: '€ 1,940.80',
  },
  {
    id: 'CGO-2026-0409',
    yacht: 'S/Y Halcyon',
    yachtShort: 'HAL', yachtColor: 'm1',
    yachtMeta: 'Chef Marius · 52m',
    received: 'Thu 11:02',
    receivedAgo: '4d',
    items: 24, flagged: 0,
    deliverBy: 'Mon 20 Apr',
    deliverTime: '14:00 · Antibes',
    status: 'dispatch',
    statusLbl: 'Out for delivery',
    value: '€ 2,114.60',
  },
  {
    id: 'CGO-2026-0405',
    yacht: 'M/Y Lumen',
    yachtShort: 'LUM', yachtColor: 'm4',
    yachtMeta: 'Chief stew Ria · 66m',
    received: 'Wed 08:40',
    receivedAgo: '5d',
    items: 12, flagged: 1,
    deliverBy: 'Wed 15 Apr',
    deliverTime: 'delivered',
    status: 'issues',
    statusLbl: '2 items short',
    value: '€ 1,428.00',
  },
];

export const LINE_ITEMS = [
  { cat: 'GALLEY · PRODUCE', name: 'Yellow plum tomatoes', sku: 'PRD-TOM-YP', qty: '4.0', unit: 'kg', price: null, total: null,
    action: 'sub', sub: { name: 'Datterini tomatoes · Sicily', price: '€ 9.20', note: 'Out of season. Datterini are the closest match — firmer, similar sweetness. Approved for substitution.' } },
  { cat: 'GALLEY · PRODUCE', name: 'Heirloom cucumbers', sku: 'PRD-CUC-HR', qty: '2.5', unit: 'kg', price: '€ 4.80', total: '€ 12.00', action: 'ok' },
  { cat: 'GALLEY · PRODUCE', name: 'Baby fennel · bunch', sku: 'PRD-FNL-BY', qty: '6', unit: 'bunch', price: '€ 3.90', total: '€ 23.40', action: 'ok' },
  { cat: 'GALLEY · DAIRY', name: 'Burrata 500g · Puglia DOP', sku: 'DRY-BUR-500', qty: '8', unit: 'unit', price: null, total: null,
    action: 'sub', sub: { name: 'Burrata 250g · Puglia DOP × 16', price: '€ 7.40', note: 'Discontinued in 500g format. Suggesting 16× 250g — same producer, same price/kg, fresher turn.' } },
  { cat: 'GALLEY · DAIRY', name: 'Normandie butter, salted', sku: 'DRY-BTR-NS', qty: '3', unit: 'kg', price: '€ 18.40', total: '€ 55.20', action: 'ok' },
  { cat: 'GALLEY · MEAT', name: 'Côte de bœuf · dry-aged 40d', sku: 'MEA-CDB-40', qty: '4', unit: 'unit', price: '€ 88.00', oldPrice: '€ 82.00', total: '€ 352.00', action: 'price',
    note: { who: 'Luca', text: 'Price up €6/unit from March — feed costs. Flagged for yacht approval.' } },
  { cat: 'GALLEY · FISH', name: 'Loup de mer, whole · 1.2kg', sku: 'FSH-LDM-12', qty: '6', unit: 'unit', price: '€ 42.00', total: '€ 252.00', action: 'ok' },
  { cat: 'BAR · WINE', name: 'Domaine Ott, Clos Mireille rosé 2023', sku: 'WIN-OTT-CM23', qty: '24', unit: 'btl', price: '€ 38.00', total: '€ 912.00', action: 'ok' },
  { cat: 'BAR · SPIRITS', name: 'Grey Goose 1.75L', sku: 'SPR-GGS-175', qty: '3', unit: 'btl', price: '€ 82.00', total: '€ 246.00', action: 'ok' },
  { cat: 'INTERIOR · DRY', name: 'Fiji water, still · 330ml × 24', sku: 'INT-FJW-330', qty: '10', unit: 'case', price: '€ 24.60', total: '€ 246.00', action: 'ok' },
];

export const CATALOGUE = [
  { name: 'Yellow plum tomatoes', sku: 'PRD-TOM-YP', cat: 'Produce', unit: 'kg', price: '€ 8.40', stock: 'out', stockLbl: 'Out of season', vis: 'select', updated: '2d ago' },
  { name: 'Datterini tomatoes · Sicily', sku: 'PRD-TOM-DT', cat: 'Produce', unit: 'kg', price: '€ 9.20', stock: 'in', stockLbl: 'In stock · 42 kg', vis: 'all', updated: '4h ago' },
  { name: 'Burrata 250g · Puglia DOP', sku: 'DRY-BUR-250', cat: 'Dairy', unit: 'unit', price: '€ 7.40', stock: 'in', stockLbl: 'In stock · 88', vis: 'all', updated: 'today' },
  { name: 'Burrata 500g · Puglia DOP', sku: 'DRY-BUR-500', cat: 'Dairy', unit: 'unit', price: '€ 14.20', stock: 'out', stockLbl: 'Discontinued', vis: 'select', updated: '1w ago' },
  { name: 'Côte de bœuf · dry-aged 40d', sku: 'MEA-CDB-40', cat: 'Meat', unit: 'unit', price: '€ 88.00', stock: 'low', stockLbl: 'Low · 6 left', vis: 'all', updated: '3h ago' },
  { name: 'Loup de mer · 1.2kg', sku: 'FSH-LDM-12', cat: 'Fish', unit: 'unit', price: '€ 42.00', stock: 'in', stockLbl: 'Pre-order · 48h', vis: 'all', updated: 'today' },
  { name: 'Normandie butter, salted', sku: 'DRY-BTR-NS', cat: 'Dairy', unit: 'kg', price: '€ 18.40', stock: 'in', stockLbl: 'In stock · 22 kg', vis: 'all', updated: 'yesterday' },
  { name: 'Domaine Ott Clos Mireille rosé 2023', sku: 'WIN-OTT-CM23', cat: 'Wine', unit: 'btl', price: '€ 38.00', stock: 'in', stockLbl: 'In stock · 214', vis: 'all', updated: '5d ago' },
  { name: 'Grey Goose 1.75L', sku: 'SPR-GGS-175', cat: 'Spirits', unit: 'btl', price: '€ 82.00', stock: 'in', stockLbl: 'In stock · 36', vis: 'all', updated: '2w ago' },
  { name: 'Fiji water, still · 330ml × 24', sku: 'INT-FJW-330', cat: 'Dry stores', unit: 'case', price: '€ 24.60', stock: 'low', stockLbl: 'Low · 12 cases', vis: 'all', updated: 'today' },
  { name: 'Heirloom cucumbers', sku: 'PRD-CUC-HR', cat: 'Produce', unit: 'kg', price: '€ 4.80', stock: 'in', stockLbl: 'In stock', vis: 'all', updated: 'today' },
  { name: 'Baby fennel · bunch', sku: 'PRD-FNL-BY', cat: 'Produce', unit: 'bunch', price: '€ 3.90', stock: 'in', stockLbl: 'In stock', vis: 'all', updated: 'today' },
];

export const DELIVERIES = [
  { day: 'Monday 20 Apr', sub: 'Today · 2 runs',
    slots: [
      { time: '14:00', window: '14:00 – 15:30', yacht: 'S/Y Halcyon', loc: 'Port Vauban · Berth Q34 · Bosun Marius', color: 'm1' },
      { time: '16:00', window: '16:00 – 17:00', yacht: 'M/Y Solstice', loc: 'IYCA · Berth A14 · 18 items', color: 'm3' },
    ]
  },
  { day: 'Tuesday 21 Apr', sub: '3 runs',
    slots: [
      { time: '07:00', window: '07:00 – 09:00', yacht: 'M/Y Aether', loc: 'Port Canto, Cannes · Purser Elena', color: 'm2' },
      { time: '09:00', window: '09:00 – 10:00', yacht: 'S/Y Corvus', loc: 'IYCA · Berth B07 · Chef Tomás', color: 'm5' },
      { time: '10:30', window: '10:30 – 12:00', yacht: 'M/Y Lumen', loc: 'Port Hercule, Monaco · Chief stew Ria', color: 'm4' },
    ]
  },
  { day: 'Thursday 23 Apr', sub: '1 run · charter start',
    slots: [
      { time: '06:00', window: '06:00 – 08:00', yacht: 'M/Y Solstice', loc: 'IYCA · Berth A14 · Bosun Kai · 38 items · charter', color: 'm3', big: true },
    ]
  },
  { day: 'Friday 24 Apr', sub: '1 run',
    slots: [
      { time: '05:30', window: '05:30 – 07:00', yacht: 'M/Y Aether', loc: 'Port Canto, Cannes · top-up before guests', color: 'm2' },
    ]
  },
];

export const INVOICES = [
  { id: 'INV-2026-0218', yacht: 'M/Y Lumen', yachtShort: 'LUM', yachtColor: 'm4', issued: '04 Apr 2026', due: '18 Apr 2026', overdueDays: 14, amount: '€ 4,160.00', status: 'issues', statusLbl: 'Overdue · 14d' },
  { id: 'INV-2026-0231', yacht: 'M/Y Solstice', yachtShort: 'SOL', yachtColor: 'm3', issued: '08 Apr 2026', due: '22 Apr 2026', amount: '€ 5,240.00', status: 'new', statusLbl: 'Sent · awaiting' },
  { id: 'INV-2026-0240', yacht: 'S/Y Corvus', yachtShort: 'COR', yachtColor: 'm5', issued: '12 Apr 2026', due: '26 Apr 2026', amount: '€ 3,080.00', status: 'new', statusLbl: 'Sent · awaiting' },
  { id: 'INV-2026-0210', yacht: 'M/Y Aether', yachtShort: 'AET', yachtColor: 'm2', issued: '28 Mar 2026', due: '11 Apr 2026', amount: '€ 6,820.00', status: 'delivered', statusLbl: 'Paid · 9 Apr' },
  { id: 'INV-2026-0199', yacht: 'S/Y Halcyon', yachtShort: 'HAL', yachtColor: 'm1', issued: '22 Mar 2026', due: '05 Apr 2026', amount: '€ 2,414.00', status: 'delivered', statusLbl: 'Paid · 2 Apr' },
  { id: 'INV-2026-0187', yacht: 'M/Y Solstice', yachtShort: 'SOL', yachtColor: 'm3', issued: '15 Mar 2026', due: '29 Mar 2026', amount: '€ 7,190.00', status: 'delivered', statusLbl: 'Paid · 24 Mar' },
];

export const CLIENTS = [
  { name: 'M/Y Solstice', short: 'SOL', color: 'm3', flag: '72m · MT · charter fleet', orders: 28, ytd: '€ 82k', repeat: '97%', contact: 'Amelia Koury · Chief stew' },
  { name: 'M/Y Aether', short: 'AET', color: 'm2', flag: '58m · CH · private', orders: 19, ytd: '€ 54k', repeat: '94%', contact: 'Elena Ferraro · Purser' },
  { name: 'M/Y Lumen', short: 'LUM', color: 'm4', flag: '66m · MH · charter', orders: 22, ytd: '€ 71k', repeat: '88%', contact: 'Ria Schön · Chief stew' },
  { name: 'S/Y Corvus', short: 'COR', color: 'm5', flag: '44m · KY · private', orders: 11, ytd: '€ 28k', repeat: '100%', contact: 'Tomás Reyes · Head chef' },
  { name: 'S/Y Halcyon', short: 'HAL', color: 'm1', flag: '52m · MT · charter', orders: 14, ytd: '€ 36k', repeat: '91%', contact: 'Marius Dubois · Head chef' },
  { name: 'M/Y Istros', short: 'IST', color: 'm2', flag: '48m · CH · private', orders: 6, ytd: '€ 14k', repeat: '—', contact: 'Sophie Aran · Chief stew' },
];
